### ISSUE TITLE
Kafka Produce Config could not replicate distributed messages

### ISSUE THREAD

**Issue by yichulau** [rollno748/di-kafkameter#16]
Hi is there a configuration that allows to configure such that the messages are send in distributed manner? Because when i did a load test, the messages will only send to one partition.

For example, i had a topic called 'test-topic' and 3 partition, when i run the jmeter, it will randomly choose one partition, and send all the message to the partition, instead of evenly distributed.

Illustration:
Topic: test-topic
Amount of message to send: 5 message

Current scenario:
partition-0: 5
partition-1: 0
partition-2 : 0

Desired output (more distributed):
partition-0:1
partition-1:2
partition-3: 2

Here is my config:
<img width="713" alt="Screenshot 2023-06-29 132839" src="https://github.com/rollno748/di-kafkameter/assets/39252336/414f0dc0-872e-4748-9833-a8279e8ff649">

**Comment by rollno748** [comment]
Hello @yichulau 

If you want to circulate the distribution among the partitions then you need to set the logic using counter/JSR223 Preprcessor

And you need to define the partition number in Partition String (on the Producer sampler)

![Uploading image.png…]()

**Comment by rollno748** [comment]
Hello @yichulau 

If you want to circulate the distribution among the partitions then you need to set the logic using counter/JSR223 Preprcessor

And you need to define the partition number in Partition String (on the Producer sampler)

![image](https://github.com/rollno748/di-kafkameter/assets/18440913/8f2afba2-580a-401c-8631-83047fc3252a)

**Comment by rollno748** [comment]
Hi 

Any update on this ?

**Comment by rollno748** [comment]
Hey @yichulau 
I am closing this issue - As I don't see any response from you.
Please feel free to re-open it, if still the issue persist
