### ISSUE TITLE
Not able to add jmeter variables in producer messages

### ISSUE THREAD

**Issue by alexa22013** [rollno748/di-kafkameter#17]
<img width="378" alt="Screenshot 2023-06-30 at 6 34 08 PM" src="https://github.com/rollno748/di-kafkameter/assets/119624630/a53a4072-7f03-46c0-9a7e-9e5b0ce6e1e2">

I am trying to producer dynamic messges, but the jmeter variables are not substituted in the messages, any reason why?

**Comment by rollno748** [comment]
Hello @alexa22013 

I have validated the plugin from my end - it works fine by replacing the variables.
Can  you attach the entire testplan screenshot or a sample jmx - where i can replicate the issue you facing

**Comment by rollno748** [comment]
Hi
Do you have any update on this issue ?

**Comment by rollno748** [comment]
Hey @alexa22013
I am closing this issue - As I don't see any response from you.
Please feel free to re-open it, if still the issue persist
