### ISSUE TITLE
Issue when Max poll record is incread.

### ISSUE THREAD

**Issue by amolsr** [rollno748/di-kafkameter#22]
I tried increasing max poll record. The plugin won't work in that case.

**Comment by rollno748** [comment]
@amolsr 
When raising issues - can you please elaborate your issue?
What version of jmeter you using?
What version of plugin is used ?
Please attach relevant screenshot or jmeter.log or sample testplan created

I can't do anything about this single line

**Comment by rollno748** [comment]
Closing this issue - as there is no response

**Comment by amolsr** [comment]
If i increase the max poll record > 1 the plugin does not work. I assume the support for batch processing is not available with this plugin.

**Comment by rollno748** [comment]
Please provide more context, logs and sample test plan to replicate
