### ISSUE TITLE
Partition Support in Consumer

### ISSUE THREAD

**Issue by amolsr** [rollno748/di-kafkameter#23]

**Comment by rollno748** [comment]
Closing this issue - as theere is no response

**Comment by amolsr** [comment]
Hi @rollno748 , sorry for late response. It is more like a feature request. The plugin can only consume topic from one partition. I was looking for a setup where I can produce message in multiple topic and can consume message from multiple partition using single thread group. For now the requirement I solved by using multiple thread group running n a parallel manner.

**Comment by rollno748** [comment]
Please provide more context, logs and sample test plan to replicate
