### ISSUE TITLE
Only String Serializer Values are allowed

### ISSUE THREAD

**Issue by chusneowork** [rollno748/di-kafkameter#25]
The thing is that we need to modify the “Kafka Producer Serializer value” because for some specific message we have a different serializer, but the only value that works is “org.apache.kafka.common.serialization.StringSerializer”. I would need to use the value “org.apache.kafka.common.serialization.Serializer” or “com.tomtomwork.webfleet.components.binaryprotocol.kafka.serialization.ProtocolBlockSerializer”, but when doing so and try to send the message, there is an error

See examples of different serializers value below:
* ![image](https://github.com/user-attachments/assets/065fe5b6-379b-4103-abe1-b467cacd6c5c)
* ![image](https://github.com/user-attachments/assets/3f8c2857-c3d5-464d-8ad6-6ee797d01e15)

See the error when sending the kafka sampler below:
![image](https://github.com/user-attachments/assets/ee913f03-3b3d-4c97-bcf3-f51c2d92e51f)

In the code plugin (https://github.com/rollno748/di-kafkameter/blob/master/src/main/java/com/di/jmeter/kafka/config/KafkaProducerConfig.java#L97-L98), it seems the interface allowed is only java.io.Serialize, but I would need to be able other serializers which use/implements “org.apache.kafka.common.serialization.Serializer” instead of “org.apache.kafka.common.serialization.StringSerializer”. It seems the plugin only allows string serializer (See he error message => Can't convert value of class java.lang.String to class org.apache.kafka.common.serialization.ByteArraySerializer specified in value.serializer)

So, oher Serializer Values such as the ones below should be able to be used:
* org.apache.kafka.common.serialization.ByteArraySerializer
* org.apache.kafka.common.serialization.ByteBufferSerializer
* com.tomtomwork.webfleet.components.binaryprotocol.kafka.serialization.ProtocolBlockSerializer (Specific implementation)

Is there any way to add support for other serializers into the di-kafkaplugin?

Attached log files:
* [ResultTree-ProtocolBlockSerializer.txt](https://github.com/user-attachments/files/16193220/ResultTree-ProtocolBlockSerializer.txt)
* [ResultTree-ByteArraySerializer.txt](https://github.com/user-attachments/files/16193221/ResultTree-ByteArraySerializer.txt)
* [JmeterLog-ProtocolBlockSerializer.txt](https://github.com/user-attachments/files/16193222/JmeterLog-ProtocolBlockSerializer.txt)
* [JmeterLog-ByteArraySerializer.txt](https://github.com/user-attachments/files/16193223/JmeterLog-ByteArraySerializer.txt)

**Comment by rollno748** [comment]
Hello,

Thanks for raising this issue. 

I understand that you want to use a custom serializer for your testing. The current plugin suppports only the default key/value serializer

To implement custom serializer, you need to copy the serializer jar to the **<JMETER_HOME>/lib** directory and provide the package/class info on the place of the value serializer

I have gone through your jmeter.log file and found that you are loading 2 jars as part of the run.
1. kafka-clients-3.7.0.jar (di-kafkameter dependency) - which is expected
2. wf-components-binaryprotocol-base-70.3.0.jar - **Is this your custom serializer jar ?**

If wf-components-binaryprotocol-base-70.3.0.jar is your custom serializer jar, then ensure the package path is properly given
If wf-components-binaryprotocol-base-70.3.0.jar is not your custom serializer then you need to create one and place it 

How to Build custom serializer : [Refer here](https://www.baeldung.com/kafka-custom-serializer)

LMK, if you need any help with this.

Thanks,

**Comment by chusneowork** [comment]
Thanks @rollno748  for your quick answer.

I added the jar files to the "Add directory or jar to classpath", but now after your suggestion, I've copied the needed JAR into the <JMETER_HOME>/lib folder, see pic below:
![image](https://github.com/user-attachments/assets/a23019ae-30e9-4724-9157-ef0bdc36370a)
See below the signature of the serializer which is included/implemented already:
![image](https://github.com/user-attachments/assets/dbfa7e3b-8072-49d6-b6ab-b09e88639a98)


Then into the Kakfa producer config I put the Serializer value "com.tomtomwork.webfleet.components.binaryprotocol.kafka.serialization.ProtocolBlockSerializer"
![image](https://github.com/user-attachments/assets/6139ac54-4f60-431d-8add-4ca84e2e1ea0)


And then when executing the jmeter testplan I got error on the kafka message
"Error sending message to kafka topic : org.apache.kafka.common.errors.SerializationException: Can't convert value of class java.lang.String to class com.tomtomwork.webfleet.components.binaryprotocol.kafka.serialization.ProtocolBlockSerializer specified in value.serializer"
![image](https://github.com/user-attachments/assets/73db813b-d5db-4d93-a08e-5e9164364384)



You mentioned that the current plugin suppports only the default key/value serializer, so I am afraid I can NOT use a different default serializer no? Or what you mean with a default serializer, that "only" any of those can be used, right?
* [StringSerializer](https://kafka.apache.org/24/javadoc/org/apache/kafka/common/serialization/StringSerializer.html)
* [ShortSerializer](https://kafka.apache.org/24/javadoc/org/apache/kafka/common/serialization/ShortSerializer.html)
* [IntegerSerializer](https://kafka.apache.org/24/javadoc/org/apache/kafka/common/serialization/IntegerSerializer.html)
* [LongSerializer](https://kafka.apache.org/24/javadoc/org/apache/kafka/common/serialization/LongSerializer.html)
* [DoubleSerializer](https://kafka.apache.org/24/javadoc/org/apache/kafka/common/serialization/DoubleSerializer.html)
* [BytesSerializer](https://kafka.apache.org/24/javadoc/org/apache/kafka/common/serialization/BytesSerializer.html)

**Comment by chusneowork** [comment]
Even, using a default serializer, such as "BytesSerializer", I see this error, so I can not use any of those default serializers...

![image](https://github.com/user-attachments/assets/d341e9a0-03d0-4592-bce1-b538d0bc3620)
![image](https://github.com/user-attachments/assets/48d895a2-6375-4f64-af2c-8c1a0242eaca)


Error sending message to kafka topic : org.apache.kafka.common.errors.SerializationException: Can't convert value of class java.lang.String to class org.apache.kafka.common.serialization.**BytesSerializer** specified in value.serializer
![image](https://github.com/user-attachments/assets/7e8f0556-d720-4672-9bac-fa24fe84b561)

**Comment by rollno748** [comment]
Hello @chusneowork 

Thanks for the update.
As per the [documentation](https://javadoc.io/doc/org.apache.kafka/kafka-clients/3.3.1/index.html), it should support all the default serialization and deserialization methods.

With your serializer, it clearly says that the return type would be an Byte array.

![image](https://github.com/user-attachments/assets/9f63881e-b2de-453e-8438-f67200c7a712)

so, you should be using the following configuration for the producer

**key.serializer : org.apache.kafka.common.serialization.StringSerializer
value.serializer : org.apache.kafka.common.serialization.ByteArraySerializer**

If the above didn't work for you, you can try the following 3 ways

1. Using Json serializer 

  For JsonSerializer you can download the[ kafka-support jar](https://repo1.maven.org/maven2/org/springframework/kafka/spring-kafka/3.2.1/spring-kafka-3.2.1.jar) from mvn and place it in <JmeterDirectory>/lib/
  
  In the producer config you have configure the json serilizer
    **key.serializer : org.apache.kafka.common.serialization.StringSerializer
    value.serializer : org.springframework.kafka.support.serializer.JsonSerializer**   

2. Writing custom jsr223 pre-processor for converting your message as string
3. Compiling the plugin to support your own serialization (I have designed this in such way to pick up on the jar, not sure - why, it is not working)

**Comment by chusneowork** [comment]
@rollno748  thanks for your quick answer. I tried the mentioned steps but yet not working. (except re-compiling the plugin)

We have a working kafka generation using our own serializer writted with custom jsr223, but without using your plugin, I'd like to make it work using your di-kafkameter plugin which is really great :-)

So, I've tried to use the value.serializer you mentioned, but even though the same problem:

![image](https://github.com/user-attachments/assets/057cfbb0-d93c-415f-a589-af8be728f13c)
Response code 500 and  message error: "Error sending message to kafka topic : org.apache.kafka.common.errors.SerializationException: Can't convert value of class java.lang.String to class org.apache.kafka.common.serialization.ByteArraySerializer specified in value.serializer" 
![image](https://github.com/user-attachments/assets/5eede733-3b9d-4f1b-b57c-d4746bb08206)
![image](https://github.com/user-attachments/assets/ce970bfb-5018-480b-9cd3-3f2df412befd)


One doubt I've got is about the input for "Kafka message". I am introducing a json, but at the end the field is a String isn't? So, when the plugin gets the input kafka message is handling it as a String instead of a ByteArray or any of the types allowed no?
![image](https://github.com/user-attachments/assets/62cb7c37-307f-4fbe-a883-561a3defe8f4)
![image](https://github.com/user-attachments/assets/a7a18f4a-7009-4c86-b2c9-08f67690cfc8)
https://github.com/rollno748/di-kafkameter/blob/master/src/main/java/com/di/jmeter/kafka/sampler/KafkaProducerSampler.java#L129-L135
![image](https://github.com/user-attachments/assets/3cbadd0b-a4f2-4a99-9df7-c80328e53366)

**Comment by rollno748** [comment]
Hi @chusneowork 

I have made some changes to the plugin, that should support other serialization. I will validate and push it over the weekend.

Thanks

**Comment by chusneowork** [comment]
Nice! Thanks @rollno748 , looking forward to that version! :-)

**Comment by chusneowork** [comment]
Hi @rollno748 , is the new plugin version available? I would like to try it but I thing changes are not yet available.

**Comment by rollno748** [comment]
Hello @chusneowork 

i have pushed the code to a branch and built the plugin 

https://github.com/rollno748/di-kafkameter/releases/download/1.3/di-kafkameter-1.3.jar

Can you test this in your scenario and let me know. 

If you still see any issues, kindly share the JSR223 code, which you are using in your case - If possible

**Comment by chusneowork** [comment]
HI @rollno748 , I am trying the new di-kafkameter 1.3 you generated for me, I delete the di-kafkameter-1.2.jar from the folder lib/ext and copied the v1.3, and when I try to send message, it is failing..
![image](https://github.com/user-attachments/assets/6ded65f9-515f-4069-b5cb-e42e7561aec3)
![image](https://github.com/user-attachments/assets/6a9d44f3-a4dd-4a51-92d8-9957bafb014a)

Not sure if I am doing something wrong to try that version v1.3 of di-kafkameter. Can you support here?

Note: I put it back the version 1.2, and the message was sent as expected.

**Comment by rollno748** [comment]
@chusneowork 
Can you please attach the jmeter.log 

You can mask the hostnames, username and password with dummy values

**Comment by chusneowork** [comment]
Ei, you are right, the kafka producer name from the sampler was different than in the config element, after adjusting that, I am able to send kafka message.
Let's go to validate the serialization issue. I will inform you during today
Thanks @rollno748

**Comment by chusneowork** [comment]
@rollno748  I just did some tries, but it seems not to work yet:

My Kafka Producer Sampler Message looks like that (json text file)
![image](https://github.com/user-attachments/assets/faff57a4-4b9f-49da-93a0-93bfdbef6dfe)

After tried different Serializer values, none of them worked:

* Serializer Value: org.apache.kafka.common.serialization.ByteArraySerializer => Error sending message to kafka topic : org.apache.kafka.common.errors.SerializationException: Can't convert key of class [B to class org.apache.kafka.common.serialization.StringSerializer specified in key.serializer
![image](https://github.com/user-attachments/assets/4aa7204d-3e7f-41f5-baf1-bb0d4d3463af)
* Serializer Value: org.apache.kafka.common.serialization.ByteBufferSerializer => Error sending message to kafka topic : java.lang.IllegalArgumentException: Unsupported serializer type: org.apache.kafka.common.serialization.ByteBufferSerializer
* Serializer Value: "com.tomtom.protocol.genericjson.kafka.GenericJsonMessageKafkaSerializer" => Error sending message to kafka topic : java.lang.IllegalArgumentException: Unsupported serializer type: com.tomtom.protocol.genericjson.kafka.GenericJsonMessageKafkaSerializer
![image](https://github.com/user-attachments/assets/b5a6a429-2424-4e58-91d4-5bf6349d229c)
* Serializer Value "com.tomtomwork.webfleet.components.binaryprotocol.kafka.serialization.ProtocolBlockSerializer" => Error sending message to kafka topic : java.lang.IllegalArgumentException: Unsupported serializer type: com.tomtomwork.webfleet.components.binaryprotocol.kafka.serialization.ProtocolBlockSerializer

Only works with the String serializer (org.apache.kafka.common.serialization.StringSerializer)

**Comment by rollno748** [comment]
@chusneowork 
Can you please attach the jmeter.log 

You can mask the hostnames, username and password with dummy values

**Comment by Roby84** [comment]
@chusneowork  Hi, i have a similar problem: i'm able to load the confluent serializer but i have this error:

Error sending message to kafka topic : java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.InvalidConfigurationException: Schema being registered is incompatible with an earlier schema for subject "P08357.ITAAlertingAPI-Request.CSO_IT-value", details: [{errorType:'TYPE_MISMATCH', description:'The type (path '/') of a field in the new schema does not match with the old schema', additionalInfo:'reader type: STRING not compatible with writer type: RECORD'}, {oldSchemaVersion: 2}, {oldSchema: '{"type":"record","name":"AlertEvent",
"namespace":"...... " ; 
error code: 409

i think it can't convert the json i'm passing in the right way.
Can you help me?

Thank you

**Comment by chusneowork** [comment]
Hi @rollno748 , have you been able to check the jmeter log? Have you find something? Looking forward to your response.

Hi @Roby84 , can you share your jmeter file, or the json and the kafka configuration you are trying to send? I can try to check... However, as we are trying to fix in this thread, the problem is that with the current DI-KafkaMeter Plugin only one serializer works  (org.apache.kafka.common.serialization.StringSerializer), any other different serializer does not work.

**Comment by Roby84** [comment]
Hi @chusneowork, yes i know, i'm using the kafkaAvroSerializer of confluent. I have imported all lib required and fixed configuration. But the error is:
![image](https://github.com/user-attachments/assets/3dd87d32-ab24-4ac1-a1fa-bc9919098113)

There is a way to have more detailed error message or a stacktrace? It seems to send a string and not an avro message...

**Comment by rollno748** [comment]
Hello @chusneowork @Roby84 

i have lost my saved store due to lap crash.
Will push a fix soon. 

Apologies for the delay.

**Comment by chusneowork** [comment]
@rollno748  thanks for the heads up. Hope you did not lost a lot of stuff. Looking forward to the update

@Roby84  have you tried to enable the debug log?
![image](https://github.com/user-attachments/assets/b799256d-420b-45b4-a123-1a8a8afd30f6)

**Comment by Roby84** [comment]
Hi @chusneowork it works and says that before error:

Checking compatibility 
of reader 
{"type":"record","name":"AlertEvent","namespace":"com.ingdirect.dg.datatransferobjects.alert.avro","doc":"Event to send an alert in asynchronous way",
"fields":[{"name":"header","type":{"type":"record","name":"AlertEventHeader",
"fields":[{"name":"traceId","type":["null","string"],"doc":"Identifier",
"default":null},{"name":"messageId","type":"string","doc":"UUID"},
{"name":"origMessageId","type":["null","string"],"doc":"UUID of original event","default":null},
{"name":"source","type":"string","doc":"Application name that produced this message"}]}},{"name":"body","type":{"type":"record","name":"AlertEventBody",
"fields":[{"name":"productCode","type":"string","doc":"product code","default":"0"},
{"name":"msgDetail","type":["null",{"type":"map","values":{"type":"string","avro.java.string":"String"},"avro.java.string":"String"}],
"doc":"placeholder parameters.",
"default":null}]}}],"aliases":["Alerting"]} 
with writer "string"

so it find avro from schema registry but the writer is still string.

How i can solve?

Thank you..

**Comment by chusneowork** [comment]
@Roby84 I think the problem you have is related to the current implementation of the serialization, even you send a json the writer seems to read it as string.
I would say let's wait for the changes that @rollno748 needs to do and hope that version will work. Let's wait for it.

**Comment by chusneowork** [comment]
@rollno748 , is there any new here? Thanks in advance

**Comment by rollno748** [comment]
@chusneowork 
I have tried multiple options, seems nothing is viable to have common method to handle custom serializers.

I have implemented the default supported serializers with this plugin that should be able to typecast most of the serializzers.
will explain you how to use your custom serializer to serialize the message before sending it in sampler. I believe that is the viable option to go with.

LMK, if you want to connect to see - how it can be done

Thanks

**Comment by chusneowork** [comment]
@rollno748 sure, I would like to see how it can be done. I will try if with that I can work. Maybe  you can extend that in the documentation.
Do I need to update to the latest di-kafkameter plugin?

**Comment by Roby84** [comment]
@rollno748 do you think it can solve also my problem with avro?

**Comment by rollno748** [comment]
@Roby84 Yes, 
It should. I will write the documentation on how to use avro serialization as well 

Thanks

**Comment by rollno748** [comment]
> @rollno748 sure, I would like to see how it can be done. I will try if with that I can work. Maybe you can extend that in the documentation. Do I need to update to the latest di-kafkameter plugin?

Hey @chusneowork 
You can use the one on the release tag or I will push the latest code and publish a newer version to plugins manager soon 

Thanks

**Comment by rollno748** [comment]
Newer version of kafkameter is released on plugins manager that should support all default serializers and deserializers

For custom serializers and deserializers - we need to use the JSR223 element before sending it in the sampler.
Will write a note on the wiki to guide on using custom serializers

**Comment by chusneowork** [comment]
@rollno748 let me know when the docu (wiki) is ready in order to give a try :-) Thanks in advance

**Comment by rollno748** [comment]
@chusneowork 
Here is the guide on using custom serializer 

https://github.com/rollno748/di-kafkameter/wiki/CustomSerializerDeserializer

**Comment by chusneowork** [comment]
Thanks @rollno748  for providing new version and documentation :-) 

I've tried the new plugin version (1.3) and following steps https://github.com/rollno748/di-kafkameter/wiki/CustomSerializerDeserializer, but yet it does not work to me. (I've  sent you an email with more details)

![image](https://github.com/user-attachments/assets/f104f00f-8b22-4126-9d77-e9adbdff5e95)

![image](https://github.com/user-attachments/assets/e5b6421f-0c73-47e4-9a1f-246a5aeb0269)

**Comment by Roby84** [comment]
@chusneowork you solved the problem?

**Comment by chusneowork** [comment]
@Roby84 , yeahp, I did a session together with @rollno748  and we were able to adjust the plugin.
Customized serialized did not work, but using the Apacha Kafka Serializers available we were able to create proper kafka messages :-)
